# Using a custom PAGE's theme
title: DD(o)L
description: A light-weight CLI application!
remote_theme: pmarsceill/just-the-docs

aux_links:
  "DD(o)L on GitHub":
  - "https://github.com/michalspano/daily-dose-lang"


# Footer
footer_content: "MIT License, Copyright (c) 2021 Michal Špano. Distributed by <a href=\"https://github.com/michalspano/daily-dose-lang/blob/main/LICENSE\">.</a>"
last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Fork me on GitHub"
gh_edit_repository: "https://github.com/michalspano/daily-dose-lang" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Theme
color_scheme: "dark"